# Generated by Django 5.1.6 on 2025-06-04 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dui', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('cambio de aceite', 'Cambio de aceite'), ('revision general', 'Revisión general'), ('reparacion', 'Reparación'), ('alineado y balanceo', 'Alineado y balanceo'), ('otro', 'Otro')], max_length=30)),
                ('fecha', models.DateField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('cambio de aceite', 'Cambio de aceite'), ('revision general', 'Revisión general'), ('reparacion', 'Reparación'), ('alineado y balanceo', 'Alineado y balanceo'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='accounts.vehiculo')),
            ],
        ),
    ]
