# Generated by Django 5.1.6 on 2025-06-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='foto_costado_der',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_costado_izq',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_placa',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='foto_trasera',
            field=models.ImageField(blank=True, null=True, upload_to='vehiculos/'),
        ),
    ]
