# Generated by Django 5.2.1 on 2025-06-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_vehiculo_foto_costado_der_vehiculo_foto_costado_izq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='proximo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='repuestos_utilizados',
            field=models.TextField(blank=True, null=True),
        ),
    ]
