# Generated by Django 5.2.1 on 2025-06-06 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_mantenimiento_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dui',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{8}-\\d{1}$', message='El DUI debe tener el formato 12345678-9 (con guión)')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^\\d{8}$', message='El número de teléfono debe tener exactamente 8 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026)], verbose_name='Año del vehiculo'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='placa',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La placa debe tener un formato válido como P123-456 o P12-8F2.', regex='^[A-Z]{1,2}\\d{1,4}-[A-Z0-9]{1,4}$')]),
        ),
    ]
