# Generated by Django 5.2.1 on 2025-06-06 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_cliente_dui_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026), django.core.validators.RegexValidator('^\\d{4}$', message='El año debe ser de exactamente 4 dígitos. Debe estar entre 1980 y 2026.')], verbose_name='Año del vehiculo'),
        ),
    ]
